### ISSUE TITLE
Where to put custom latex mappings file?

### ISSUE THREAD

**Issue by fatanassow** [YellPika/vscode-latex-input#6]
This is perhaps more a question than an issue.

I have overridden the `latex-input.mappings` and supplied my own mappings file. This works, but only if I put the file inside the  package directory itself. I understand the filepath is interpreted relative to there, but it seems to me that that might be a poor place to store it. (For example, I am not sure how package upgrades deal with foreign files.) I intended to put the file right under the .vscode folder, but prepending the filename with `../../` or `..\\..\\` did not work.

Is there a way to store the file outside the package directory? Should there be? If so, where is a good place to put it? And how do I tell latex-input to find it there?

**Comment by YellPika** [comment]
I agree that the extension directory is a poor place to store user-defined mappings. I will have the extension look for mappings according to the following rules:

1. If the user sets latex-input.mappings in .vscode/settings.json, then the extension looks for the configuration file relative to the .vscode folder.
2. Otherwise (or if a file is specified but doesn't exist), the extension searches the extension directory.

If you want to override the mappings globally but don't want to store your mappings in the extension directory, you can always specify an absolute path. (Using ~ might work too but I haven't tested it.)

**Comment by fatanassow** [comment]
This sounds okay to me, but using an absolute path was the first thing I tried and it didn't work. I glanced at the code and it seems to interpret the path as relative. (Or maybe your remark refers to a change you intend to make.)

**Comment by YellPika** [comment]
Fixed by 2b64b131606ba472413ea95fc933e492d4a70213. Absolute filenames are now handled correctly and paths can use the `${workspaceFolder}` variable.
